.PHONY: clean All

All:
	@echo "----------Building project:[ PrimitiveDataTypes - Debug ]----------"
	@cd "PrimitiveDataTypes" && "$(MAKE)" -f  "PrimitiveDataTypes.mk"
clean:
	@echo "----------Cleaning project:[ PrimitiveDataTypes - Debug ]----------"
	@cd "PrimitiveDataTypes" && "$(MAKE)" -f  "PrimitiveDataTypes.mk" clean
