.PHONY: clean All

All:
	@echo "----------Building project:[ DeclaringInitializingArrays - Debug ]----------"
	@cd "DeclaringInitializingArrays" && "$(MAKE)" -f  "DeclaringInitializingArrays.mk"
clean:
	@echo "----------Cleaning project:[ DeclaringInitializingArrays - Debug ]----------"
	@cd "DeclaringInitializingArrays" && "$(MAKE)" -f  "DeclaringInitializingArrays.mk" clean
